name: Increment version of updated languages
# Increment the version for all language add-ons that were updated

on:
  push:
    branches: [ main, master ]
    paths:
      - '**resource.language.**strings.po'
      - '**resource.language.**langinfo.xml'

jobs:
  default:
    runs-on: ubuntu-latest
    name: Increment version of updated languages

    steps:

      # Checkout the current repository into a directory (repositories name)
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: ${{ github.event.repository.name }}

      # Checkout the required scripts from xbmc/weblate-supplementary-scripts into the 'scripts' directory
      - name: Checkout Scripts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: xbmc/weblate-supplementary-scripts
          path: scripts

      # Setup python version 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Generate files.json containing a list of files that were changed in the triggering commit
      - name: Get changed files
        uses: trilom/file-changes-action@v1.2.4

      # Run the python script to increment the version of all language add-ons with changes
      - name: Increment version of updated languages
        run: |
          python3 ../scripts/repo-resources/increment_version.py $HOME/files.json
        working-directory: ${{ github.event.repository.name }}

      # Create a PR with the incremented versions
      # - title/commit message: Language add-on versions incremented
      # - body: Language add-on versions incrementing triggered by {github.sha}
      - name: Create PR for incremented versions
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          commit-message: Language add-on versions incremented
          title: Language add-on versions incremented
          body: Language add-on versions incrementing triggered by ${{ github.sha }}
          branch: inc-ver
          delete-branch: true
          path: ./${{ github.event.repository.name }}
