name: Binary Scripts - pytest

on:
  push:
    branches: [ master, main ]
    paths:
      - '**binary**'

  pull_request:
    branches: [ master, main ]
    paths:
      - '**binary**'

jobs:

  pytest:
    if: github.repository == 'xbmc/weblate-supplementary-scripts'

    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest

      - name: pytest
        id: pytest
        run: |
          pytest
        working-directory: ${{ github.event.repository.name }}/binary
